# compare centered vs noncentered parameterizations
library(rstan)

parlist <- c("alpha0", "gamma0", "alpha1", "gamma1", "sigma_beta0", "sigma_beta1", "sigma_y")
load("/Users/susanna/projects/cluster_sampling/output/stanfit_usesizes_0_nclusters_5_nunits_5pct_simno_1_knowsizes_centered.RData")
par(oma=c(0,0,0,0))
pairs(fit, pars = parlist, log = c(5:7))
title("usz 0, centered")
rm(fit)
load("/Users/susanna/projects/cluster_sampling/output/stanfit_usesizes_0_nclusters_5_nunits_5pct_simno_1_knowsizes_noncentered.RData")
par(oma=c(0,0,0,0))
pairs(fit, pars = parlist, log = c(5:7))
title("usz 0, noncentered")
rm(fit)
load("/Users/susanna/projects/cluster_sampling/output/stanfit_usesizes_1_nclusters_5_nunits_5pct_simno_1_knowsizes_centered.RData")
par(oma=c(0,0,0,0))
pairs(fit, pars = parlist, log = c(5:7))
title("usz 1, centered")
rm(fit)
load("/Users/susanna/projects/cluster_sampling/output/stanfit_usesizes_1_nclusters_5_nunits_5pct_simno_1_knowsizes_noncentered.RData")
par(oma=c(0,0,0,0))
pairs(fit, pars = parlist, log = c(5:7))
title("usz 1, noncentered")
rm(fit)
